sudo: required
dist: trusty


services:
  - docker # required, but travis uses older version of docker :(
install:
  - pip install docker-compose

jobs:
  include:
    - stage: build docker image
      script:
      - docker --version
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t mcano/io18 .
      - docker images
      - docker push mcano/io18