version: "3.5"
services:
  web:
    image: ${IMAGE_NAME:-mcano/compose-to-swarm:v1}
    environment:
      - REDIS_HOST=redis
      - FOO=${FOO:-BAR}
    ports:
      - target: 5000
        published: 5000
    networks:
      - skynet

  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
    networks:
      skynet:

networks:
  skynet:
