version: "3.5"
services:
  web:
    image: mcano/io-extended
    command: python app.py
    environment:
      REDIS_HOST: redis
    ports:
      - target: 5000
        published: 5000
    networks:
      - skynet
  redis:
    image: "redis:alpine"
    networks:
      skynet:

networks:
  skynet:
