version: "3.5"
services:
  web:
    image: ${IMAGE_NAME:-mcano/io-extended}
    command: python app.py
    environment:
      REDIS_HOST: redis
    ports:
      - target: 5000
        published: 5000
    networks:
      - skynet
  deploy:
      replicas: ${DEPLOYMENT_REPLICAS:-4}
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
  ports:
  - 5000:5000
  redis:
    image: "redis:alpine"
    networks:
      skynet:

networks:
  skynet:
